pipeline{
    agent{
        label "node"
    }
    triggers {
        pollSCM '*/5 * * * *'
    }    
    stages{
        stage("build"){
            steps{
                echo "========executing build======="
            }
            post{
                always{
                    echo "========always========"
                    sh '''
                    npm install
                    npm run build
                    '''
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
         stage("test"){
            steps{
                echo "========executing test======="
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
         stage("deploy"){
            steps{
                echo "========executing deploy======="
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========A executed successfully========"
                }
                failure{
                    echo "========A execution failed========"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed========"
        }
    }
}
