pipeline{
    agent{
        label "docker-agent-node"
    }
    tools{
        nodejs 'node'
    }
    triggers {
        githubPush()
    }   
    stages{
        stage("Installation Of Dependencies"){           
            steps{
                echo "========Installing node modules======="
            }
            post{
                always{
                    sh '''
                    cd sepient/ 
                    npm install
                    '''
                }
                success{
                    echo "========Node module installation done========"
                }
                failure{
                    echo "========Node module installation failed========"
                }
            }
        }
        stage("Build"){
            steps{
                echo "========Building production atifacts======="
            }
            post{
                always{
                    sh '''
                    cd sepient/
                    npm run build
                    '''
                }
                success{
                    echo "========Production atifacts built successfully========"
                }
                failure{
                    echo "========Production atifacts failed========"
                }
            }
        }
         stage("test"){
            steps{
                echo "========executing test======="
            }
            post{
                always{
                     sh '''
                    cd sepient/
                    npm run test:coverage
                    '''
                }
                success{
                    echo "========Test completed successfully========"
                }
                failure{
                    echo "========Test execution failed========"
                }
            }
        }
         stage("deploy"){
            steps{
                echo "========executing deploy======="
            }
            post{
                always{
                    echo "========always========"
                }
                success{
                    echo "========Application deployed successfully========"
                }
                failure{
                    echo "========Application deployement failed========"
                }
            }
        }
    }
    post{
        always{
            echo "========always========"
        }
        success{
            echo "========pipeline executed successfully ========"
        }
        failure{
            echo "========pipeline execution failed ========"
        }
    }
}
